class StatefulMultiplier:
    def __init__(self, initial_state: float) -> None: ...
    def set_internal_state(self, value: float) -> None: ...
    def multiply_by_internal_state(self, value: float) -> float: ...
